controller_list:
  - name: fake_front_left_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - front_left_arm_joint1
      - front_left_arm_joint2
      - front_left_arm_joint3
      - front_left_arm_joint4
      - front_left_arm_joint5
      - front_left_arm_joint6
      - front_left_arm_joint7
  - name: fake_front_right_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - front_right_arm_joint1
      - front_right_arm_joint2
      - front_right_arm_joint3
      - front_right_arm_joint4
      - front_right_arm_joint5
      - front_right_arm_joint6
      - front_right_arm_joint7
  - name: fake_rear_left_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - rear_left_arm_joint1
      - rear_left_arm_joint2
      - rear_left_arm_joint3
      - rear_left_arm_joint4
      - rear_left_arm_joint5
      - rear_left_arm_joint6
      - rear_left_arm_joint7
  - name: fake_rear_right_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - rear_right_arm_joint1
      - rear_right_arm_joint2
      - rear_right_arm_joint3
      - rear_right_arm_joint4
      - rear_right_arm_joint5
      - rear_right_arm_joint6
      - rear_right_arm_joint7
  - name: fake_front_left_hand_controller
    type: $(arg fake_execution_type)
    joints:
      - front_left_arm_finger_joint1
  - name: fake_front_right_hand_controller
    type: $(arg fake_execution_type)
    joints:
      - front_right_arm_finger_joint1
  - name: fake_rear_left_hand_controller
    type: $(arg fake_execution_type)
    joints:
      - rear_left_arm_finger_joint1
  - name: fake_rear_right_hand_controller
    type: $(arg fake_execution_type)
    joints:
      - rear_right_arm_finger_joint1
  - name: fake_multi_arms_group_controller
    type: $(arg fake_execution_type)
    joints:
      - front_left_arm_joint1
      - front_left_arm_joint2
      - front_left_arm_joint3
      - front_left_arm_joint4
      - front_left_arm_joint5
      - front_left_arm_joint6
      - front_left_arm_joint7
      - front_right_arm_joint1
      - front_right_arm_joint2
      - front_right_arm_joint3
      - front_right_arm_joint4
      - front_right_arm_joint5
      - front_right_arm_joint6
      - front_right_arm_joint7
      - rear_left_arm_joint1
      - rear_left_arm_joint2
      - rear_left_arm_joint3
      - rear_left_arm_joint4
      - rear_left_arm_joint5
      - rear_left_arm_joint6
      - rear_left_arm_joint7
      - rear_right_arm_joint1
      - rear_right_arm_joint2
      - rear_right_arm_joint3
      - rear_right_arm_joint4
      - rear_right_arm_joint5
      - rear_right_arm_joint6
      - rear_right_arm_joint7
initial:  # Define initial robot poses per group
  - group: front_left_arm
    pose: home
  - group: front_right_arm
    pose: home
  - group: rear_left_arm
    pose: home
  - group: rear_right_arm
    pose: home
  - group: front_left_hand
    pose: open
  - group: front_right_hand
    pose: open
  - group: rear_left_hand
    pose: open
  - group: rear_right_hand
    pose: open