controller_list:
  - name: front_right_arm_trajectory_controller
      action_ns: follow_joint_trajectory
      type: FollowJointTrajectory
      default: True
      joints:
      - front_right_arm_joint1
      - front_right_arm_joint2
      - front_right_arm_joint3
      - front_right_arm_joint4
      - front_right_arm_joint5
      - front_right_arm_joint6
      - front_right_arm_joint7
  - name: front_left_arm_trajectory_controller
      action_ns: follow_joint_trajectory
      type: FollowJointTrajectory
      default: True
      joints:
      - front_left_arm_joint1
      - front_left_arm_joint2
      - front_left_arm_joint3
      - front_left_arm_joint4
      - front_left_arm_joint5
      - front_left_arm_joint6
      - front_left_arm_joint7
  - name: rear_right_arm_trajectory_controller
      action_ns: follow_joint_trajectory
      type: FollowJointTrajectory
      default: True
      joints:
      - rear_right_arm_joint1
      - rear_right_arm_joint2
      - rear_right_arm_joint3
      - rear_right_arm_joint4
      - rear_right_arm_joint5
      - rear_right_arm_joint6
      - rear_right_arm_joint7
  - name: rear_left_arm_trajectory_controller
      action_ns: follow_joint_trajectory
      type: FollowJointTrajectory
      default: True
      joints:
      - rear_left_arm_joint1
      - rear_left_arm_joint2
      - rear_left_arm_joint3
      - rear_left_arm_joint4
      - rear_left_arm_joint5
      - rear_left_arm_joint6
      - rear_left_arm_joint7

  - name: front_right_hand_controller
      action_ns: follow_joint_trajectory
      type: FollowJointTrajectory
      default: true
      joints:
      - front_right_arm_finger_joint1

  - name: front_left_hand_controller
      action_ns: follow_joint_trajectory
      type: FollowJointTrajectory
      default: true
      joints:
      - front_left_arm_finger_joint1
      
  - name: rear_right_hand_controller
      action_ns: follow_joint_trajectory
      type: FollowJointTrajectory
      default: true
      joints:
      - rear_right_arm_finger_joint1

  - name: rear_left_hand_controller
      action_ns: follow_joint_trajectory
      type: FollowJointTrajectory
      default: true
      joints:
      - rear_left_arm_finger_joint1