front_right_arm_trajectory_controller:
    type: "position_controllers/JointTrajectoryController"
    joints:
        - front_right_arm_joint1
        - front_right_arm_joint2
        - front_right_arm_joint3
        - front_right_arm_joint4
        - front_right_arm_joint5
        - front_right_arm_joint6
        - front_right_arm_joint7
    constraints:
        goal_time: 0.6
        stopped_velocity_tolerance: 0.05
        right_arm_joint1: {trajectory: 0.1, goal: 0.1}
        right_arm_joint2: {trajectory: 0.1, goal: 0.1}
        right_arm_joint3: {trajectory: 0.1, goal: 0.1}
        right_arm_joint4: {trajectory: 0.1, goal: 0.1}
        right_arm_joint5: {trajectory: 0.1, goal: 0.1}
        right_arm_joint6: {trajectory: 0.1, goal: 0.1}
        right_arm_joint7: {trajectory: 0.1, goal: 0.1}
    stop_trajectory_duration: 0.5
    state_publish_rate:  25
    action_monitor_rate: 10

front_left_arm_trajectory_controller:
    type: "position_controllers/JointTrajectoryController"
    joints:
        - front_left_arm_joint1
        - front_left_arm_joint2
        - front_left_arm_joint3
        - front_left_arm_joint4
        - front_left_arm_joint5
        - front_left_arm_joint6
        - front_left_arm_joint7
    constraints:
        goal_time: 0.6
        stopped_velocity_tolerance: 0.05
        left_arm_joint1: {trajectory: 0.1, goal: 0.1}
        left_arm_joint2: {trajectory: 0.1, goal: 0.1}
        left_arm_joint3: {trajectory: 0.1, goal: 0.1}
        left_arm_joint4: {trajectory: 0.1, goal: 0.1}
        left_arm_joint5: {trajectory: 0.1, goal: 0.1}
        left_arm_joint6: {trajectory: 0.1, goal: 0.1}
        left_arm_joint7: {trajectory: 0.1, goal: 0.1}
    stop_trajectory_duration: 0.5
    state_publish_rate:  25
    action_monitor_rate: 10

rear_right_arm_trajectory_controller:
    type: "position_controllers/JointTrajectoryController"
    joints:
        - rear_right_arm_joint1
        - rear_right_arm_joint2
        - rear_right_arm_joint3
        - rear_right_arm_joint4
        - rear_right_arm_joint5
        - rear_right_arm_joint6
        - rear_right_arm_joint7
    constraints:
        goal_time: 0.6
        stopped_velocity_tolerance: 0.05
        right_arm_joint1: {trajectory: 0.1, goal: 0.1}
        right_arm_joint2: {trajectory: 0.1, goal: 0.1}
        right_arm_joint3: {trajectory: 0.1, goal: 0.1}
        right_arm_joint4: {trajectory: 0.1, goal: 0.1}
        right_arm_joint5: {trajectory: 0.1, goal: 0.1}
        right_arm_joint6: {trajectory: 0.1, goal: 0.1}
        right_arm_joint7: {trajectory: 0.1, goal: 0.1}
    stop_trajectory_duration: 0.5
    state_publish_rate:  25
    action_monitor_rate: 10

rear_left_arm_trajectory_controller:
    type: "position_controllers/JointTrajectoryController"
    joints:
        - rear_left_arm_joint1
        - rear_left_arm_joint2
        - rear_left_arm_joint3
        - rear_left_arm_joint4
        - rear_left_arm_joint5
        - rear_left_arm_joint6
        - rear_left_arm_joint7
    constraints:
        goal_time: 0.6
        stopped_velocity_tolerance: 0.05
        left_arm_joint1: {trajectory: 0.1, goal: 0.1}
        left_arm_joint2: {trajectory: 0.1, goal: 0.1}
        left_arm_joint3: {trajectory: 0.1, goal: 0.1}
        left_arm_joint4: {trajectory: 0.1, goal: 0.1}
        left_arm_joint5: {trajectory: 0.1, goal: 0.1}
        left_arm_joint6: {trajectory: 0.1, goal: 0.1}
        left_arm_joint7: {trajectory: 0.1, goal: 0.1}
    stop_trajectory_duration: 0.5
    state_publish_rate:  25
    action_monitor_rate: 10

front_right_hand_controller:
    type: "effort_controllers/JointTrajectoryController"
    joints:
        - front_right_arm_finger_joint1
    gains:
        front_right_arm_finger_joint1:  {p: 50.0, d: 1.0, i: 0.01, i_clamp: 1.0}

front_left_hand_controller:
    type: "effort_controllers/JointTrajectoryController"
    joints:
        - front_left_arm_finger_joint1
    gains:
        front_left_arm_finger_joint1:  {p: 50.0, d: 1.0, i: 0.01, i_clamp: 1.0}

rear_right_hand_controller:
    type: "effort_controllers/JointTrajectoryController"
    joints:
        - rear_right_arm_finger_joint1
    gains:
        rear_right_arm_finger_joint1:  {p: 50.0, d: 1.0, i: 0.01, i_clamp: 1.0}

rear_left_hand_controller:
    type: "effort_controllers/JointTrajectoryController"
    joints:
        - rear_left_arm_finger_joint1
    gains:
        rear_left_arm_finger_joint1:  {p: 50.0, d: 1.0, i: 0.01, i_clamp: 1.0}